#!/bin/bash

# Credits for this script go to laheller
# https://github.com/gphoto/libgphoto2/issues/335#issuecomment-881946081


REPO_NAME=$1
REPO_URL=$2
BINARY_PATH=${3:-lib/$REPO_NAME.so}
COPY_FROM=${4:-GIT}

if [ ! -d $GB_WORKSPACE ]; then
    echo "Workspace does not exist, create it...";
    echo -n "Creating ${GB_WORKSPACE} ...";
    mkdir -p $GB_WORKSPACE
    if [ $? -eq 0 ]; then
        echo "Done";
    else
        echo "Failed";
        exit 0;
    fi
fi
#
# set whatever target dir for installation, but do NOT set to /usr
export PREFIX=$GB_WORKSPACE/_prefix
mkdir -p $PREFIX


cd $GB_WORKSPACE/${REPO_NAME};


# build will happen in this dir
rm -rf _build
mkdir _build
cd _build



# additional settings for compiler
# we can also specify additional compiler flags
export CFLAGS="${CFLAGS} --sysroot=${SYSROOT} -I${SYSROOT}/usr/include -I${PREFIX}/include -fPIE -std=c99"
export CPPFLAGS="${CFLAGS}"

# we can also specify additional linker flags
export LDFLAGS="${LDFLAGS} --sysroot=${SYSROOT} -L${SYSROOT}/usr/lib -L${PREFIX}/lib -pie"

# Set pkgconfig search path
export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig
export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig

# run "../configure --help" to see all available command line switches, sometimes they must be tweaked
# here is the main difference when we build a project from sources for Android platform
../configure --host=${TARGET} --with-sysroot=${SYSROOT} --disable-rpath --prefix=${PREFIX} ${CONFIGURE_ARGS}

make -j6

make install

echo "Architecture of the built library:"
$READELF -a ${PREFIX}/${BINARY_PATH} | grep Machine:
