#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
# set GB_HOME: gphoto2_builder_home
export GB_HOME=$DIR
export GB_WORKSPACE="$DIR/workspace"

if [ ! -e $NDK/ndk-build ]; then
  echo "NDK environment variable not set correctly, exit...";
  exit -1;
fi

. $GB_HOME/setenv.sh

if [ ! -e $SYSROOT/usr/include/stdio.h ]; then
  echo "NDK SYSROOT environment variable not set correctly, exit...";
  echo "SYSROOT set to $SYSROOT"
  exit -1;
fi

#echo "$@"

# libgphoto2 depends on several libraries, so build them first
# $DIR/build-libexif 
$DIR/build-libtool
exit 0;
$DIR/build-libusb
$DIR/build-libgphoto2

# Then uild gphoto2
$DIR/build-libpopt
$DIR/build-gphoto2

echo "Done! Build artifacts are in /workspace/_prefix"
